# Generated by Django 6.0.4 on 2026-04-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos', models.IntegerField(default=50)),
                ('dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SOCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('maquinas_completadas', models.ManyToManyField(blank=True, to='api.maquina')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
