# Generated by Django 6.0.4 on 2026-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maquina_socprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='socprofile',
            name='normativa_aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
